language: node_js
node_js:
- '5'
- '4.2'

# Run on new infrastructure
sudo: false

# Some newer nodejs modules need a c++ compiler
env:
  - CXX=g++-4.8

# Get heroku toolbelt
addons:
  apt:
    sources:
    - heroku
    - ubuntu-toolchain-r-test
    packages:
    - heroku-toolbelt
    - g++-4.8