language: node_js
node_js:
- '4.2'

# Run on new infrastructure
sudo: false

# Get heroku toolbelt
addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt

# Run toolbelt to make sure it works
before_script:
- heroku --version #just test if this works

# Run tests
# script:
# - npm test